version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/araujomarc/araujomarc/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  site-vitoria:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          from django.db import models
          
          from pagina1.models import Gato
          
          
          class Base(models.Model):
              numero_na_fila = models.CharField(max_length=255)
          
          
          
          class Cliente(Base):
              nome = models.CharField(max_length=255  )
              telefone = models.CharField(max_length=255)
              localidade = models.CharField(max_length=255)
              preferencia_cor = models.CharField(max_length=255)
              preferencia_sexo = models.CharField(max_length=255)
              valor_entrega = models.CharField(max_length=255)
              gato = models.ForeignKey(Gato, related_name='cliente', on_delete=models.CASCADE,default='')
          

workflows:
  my-custom-workflow:
    jobs:
      - site-vitoria